In [8]:

'''
While satser uppgift 1
skriv ett program som beräknar följande aritmetiska summa med hjälp av while-sats
'''

s = 0
nummer = 0

while s < 100:
    s += 1
    nummer += s

print(f"1+2+3+...+99+100 = {nummer}")

1+2+3+...+99+100 = 5050


In [10]:

s = 0
nummer = 0

while s < 99:
    s += 2
    nummer += s

print(f"1+3+5+...+99 = {nummer}")


1+3+5+...+99 = 2550


In [35]:
import random as rnd

gissning = float(input("Gissa ett tal mellan 0 till 100: "))
tal = rnd.randint(0,101)

while gissning != tal:
    gissning = tal - gissning
    gissning = float(input("Gissa igenom: "))
     
print("Rätt svar")


ValueError: could not convert string to float: ''

In [17]:

'''
1L mjölk 1500000 bakterier
I rumstemp ökar antalet bakterier med 50% varje timme
Mjölk blir sur när bakterierna överstiger 10000000 st
Hur många timmar tills mjölken blir sur?
'''

b = 1500000

t = 0

while b < 10000000:
    b *= 1.5
    t += 1

print(f"{t} timmar för {b} bakterier")

print(f"Det tar {t} timmar tills mjölken blir sur")




5 timmar för 11390625.0 bakterier
Det tar 5 timmar tills mjölken blir sur


In [23]:
import matplotlib.pyplot
import numpy as np

bakterier = 1.5e6  #bakterier
surt = 1e7 #surt
faktor = 1.5
timmar = 0  #timmar

y_bakterier = [bakterier] #lista som ska håla allt ihop

while bakterier < surt:
    bakterier = faktor*bakterier
    y_bakterier.append(bakterier) #bakterier läggs in i listan
    timmar += 1

    x_timmar = np.arange(timmar)

    print(x_timmar)

print(f"{timmar} timmar för att mjölken skall bri sur")
print(y_bakterier)

plt.plot(x_timmar, y_bakterier,"*-")
plt.xlabel("timmar")
plt.ylabel("bakterier")
plt.title("bakteriertillväxt i mjölken i rumstemperatur")

[0]
[0 1]
[0 1 2]
[0 1 2 3]
[0 1 2 3 4]
5 timmar för att mjölken skall bri sur
[1500000.0, 2250000.0, 3375000.0, 5062500.0, 7593750.0, 11390625.0]


NameError: name 'plt' is not defined